version: 0.0
os: linux
files:
  - source: myapp.war
    destination: /var/lib/tomcat9/webapps
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: tomcat
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: tomcat
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: tomcat
