version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/hello-world-0.0.1-SNAPSHOT.war myapp.war
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - myapp.war

