version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - apt-get update && apt-get install -y maven
      
  build:
    commands:
      - echo Building Maven project
      - mvn package
      - mv target/hello-world-0.0.1-SNAPSHOT.war myapp.war
artifacts:
  files:
    - myapp.war
